devices:
  samplerate: 44100
  chunksize: 1024
  queuelimit: 4
  capture:
    type: Alsa
    channels: 2
    device: hw:Loopback,1,0
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: hw:IanCanadaDAC
    format: S32LE
filters:
  master_gain:
    type: Gain
    parameters:
      gain: 0
      inverted: false
  subsonic_hp:
    type: Biquad
    parameters:
      type: Highpass
      freq: 20
      q: 0.707
  night_mode_bass_cut:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 150
      q: 0.707
      gain: -8
  night_mode_gain:
    type: Gain
    parameters:
      gain: 2
      inverted: false
  balance_cut_right:
    type: Gain
    parameters:
      gain: -3
      inverted: false
pipeline:
  - type: Filter
    channel: 0
    names:
      - master_gain
      - subsonic_hp
      - night_mode_bass_cut
      - night_mode_gain
  - type: Filter
    channel: 1
    names:
      - master_gain
      - subsonic_hp
      - night_mode_bass_cut
      - night_mode_gain
      - balance_cut_right
