music_directory    "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file            "/var/lib/mpd/tag_cache"
log_file           "/var/log/mpd/mpd.log"
pid_file           "/run/mpd/pid"
state_file         "/var/lib/mpd/state"
sticker_file       "/var/lib/mpd/sticker.sql"

user               "mpd"
bind_to_address    "any"
port               "6600"

# Output going to ALSA loopback to be processed by CamillaDSP
audio_output {
    type            "alsa"
    name            "ALSA Loopback for CamillaDSP"
    device          "hw:Loopback,0,0" # Loopback device
    mixer_type      "software"
}

# Optional output for visualization directly if needed
# audio_output {
#     type            "fifo"
#     name            "my_fifo"
#     path            "/tmp/mpd.fifo"
#     format          "44100:16:2"
# }
