// Shairport Sync configuration for Apple AirPlay
// Routes audio to ALSA loopback for CamillaDSP processing

general = {
  name = "HiFi Streamer"; // The name that will show up on Apple devices
  interpolation = "soxr";
  output_backend = "alsa";
  mdns_backend = "avahi";
};

alsa = {
  // We route Airplay directly to the ALSA loopback device
  // so CamillaDSP picks it up on hw:Loopback,1,0
  output_device = "hw:Loopback,0,0";
  mixer_control_name = "PCM";
};

sessioncontrol = {
  run_this_before_play_begins = "/usr/bin/curl -X POST http://localhost:3001/api/webhooks/state -H \"Content-Type: application/json\" -d '{\"state\":\"play\", \"source\":\"AirPlay\"}'";
};
